import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/toaster";
import { headers } from "next/headers";
import { isMobile } from "@/utils/isMobile";
import { Box, Flex, Text } from "@chakra-ui/react";

const JosefinSans = localFont({
  src: [
    {
      path: "./fonts/static/JosefinSans-Regular.ttf",
      weight: "400",
    },
    {
      path: "./fonts/static/JosefinSans-Bold.ttf",
      weight: "700",
    },
    {
      path: "./fonts/static/JosefinSans-Medium.ttf",
      weight: "500",
    },
    {
      path: "./fonts/static/JosefinSans-Light.ttf",
      weight: "300",
    },
    {
      path: "./fonts/static/JosefinSans-SemiBold.ttf",
      weight: "600",
    },
  ],
  variable: "--font-josefin-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userAgent = headers().get("user-agent") || "";
  const isMobileDevice = isMobile(userAgent);
  return (
    <html lang="en">
      <body className={`${JosefinSans.variable} antialiased`}>
        <Provider>
          <Toaster />
          <StoreProvider>
            <Box
              bgGradient="to-r"
              gradientFrom="red.200"
              gradientTo="blue.200"
              minH="100vh"
            >
              {!isMobileDevice ? (
                children
              ) : (
                <Flex alignContent={"center"} justifyContent={"center"}>
                  <Text fontWeight={"bold"} textStyle={"2xl"}>
                    Mobile Version is not available
                  </Text>
                </Flex>
              )}
            </Box>
          </StoreProvider>
        </Provider>
      </body>
    </html>
  );
}
